version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 --port=5000"
    depends_on:
      - postgres
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1 # Instead of FLASK_ENV (deprecated in Flask 2.3+)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecure
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,sns,lambda
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # TODO: Need to fix hot-reload when changes locally
  # frontend:
  #   build: ./frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app # mount source for live reload
  #     - /app/node_modules # avoid overwriting node_modules with empty volume
volumes:
  pgdata:
  localstack_data:
