import os

# shipstation
SHIP_STATION_API_KEY = os.getenv("SHIP_STATION_API_KEY")
SHIP_STATION_API_SECRET = os.getenv("SHIP_STATION_API_SECRET")

# localstack
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION")
LOCALSTACK_HOST = os.getenv("LOCALSTACK_HOST")
S3_BUCKET = os.getenv("S3_BUCKET")
