import os

# shipstation
SHIP_STATION_API_KEY = os.getenv("SHIP_STATION_API_KEY")
SHIP_STATION_API_SECRET = os.getenv("SHIP_STATION_API_SECRET")

# localstack
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION")
LOCALSTACK_HOST = os.getenv("LOCALSTACK_HOST")
S3_BUCKET = os.getenv("S3_BUCKET")

# auth
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")

# CSV file paths
PRODUCT_CSV_FILE_PATH = os.getenv("PRODUCT_CSV_FILE_PATH")
ORDER_HISTORY_CSV_FILE_PATH = os.getenv("ORDER_HISTORY_CSV_FILE_PATH")
EMPLOYEE_CSV_FILE_PATH = os.getenv("EMPLOYEE_CSV_FILE_PATH")

# Emailer
MAIL_SERVER = os.getenv("MAIL_SERVER")
MAIL_PORT = os.getenv("MAIL_PORT")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_USE_TLS = os.getenv("MAIL_USE_TLS")
