"""create orders table

Revision ID: 2e8515fdba71
Revises: 
Create Date: 2025-08-06 10:27:47.403798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8515fdba71'
down_revision = 'f78653aa3bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
                    sa.Column('id', sa.UUID(), primary_key=True,
                              default=sa.text('uuid_generate_v4()')),
                    sa.Column('customer_id', sa.UUID(),
                              sa.ForeignKey('customers.id'), nullable=False),
                    sa.Column('model_number', sa.String(
                        length=50), nullable=False),
                    sa.Column('issues', sa.Text(), nullable=True),
                    sa.Column('case_number', sa.String(
                        length=50), nullable=True),
                    sa.Column('sales_order', sa.String(
                        length=50), nullable=True),
                    sa.Column('assign', sa.String(length=100), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=True),
                    sa.Column('serial', sa.String(length=100), nullable=True),
                    sa.Column('solution', sa.Text(), nullable=True),
                    sa.Column('action', sa.Text(), nullable=True),
                    sa.Column('tracking', sa.String(
                        length=100), nullable=True),
                    sa.Column('return_status', sa.String(
                        length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    op.drop_table('cases')
