"""create orders table

Revision ID: 2e8515fdba71
Revises: 
Create Date: 2025-08-06 10:27:47.403798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8515fdba71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('phone_number', sa.String(
                        length=20), nullable=False),
                    sa.Column('model_number', sa.String(
                        length=50), nullable=False),
                    sa.Column('issues', sa.Text(), nullable=True),
                    sa.Column('case', sa.String(length=50), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('sales_order', sa.String(
                        length=50), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('address', sa.String(length=200), nullable=True),
                    sa.Column('street', sa.String(length=100), nullable=True),
                    sa.Column('city', sa.String(length=100), nullable=True),
                    sa.Column('zip_code', sa.String(length=20), nullable=True),
                    sa.Column('state', sa.String(length=100), nullable=True),
                    sa.Column('country', sa.String(length=100), nullable=True),
                    sa.Column('assign', sa.String(length=100), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=True),
                    sa.Column('serial', sa.String(length=100), nullable=True),
                    sa.Column('solution', sa.Text(), nullable=True),
                    sa.Column('action', sa.Text(), nullable=True),
                    sa.Column('tracking', sa.String(
                        length=100), nullable=True),
                    sa.Column('return_status', sa.String(
                        length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    op.drop_table('orders')
