"""Create users table

Revision ID: 3e3574d2e514
Revises: 9ac2d0c8d30f
Create Date: 2025-08-15 21:26:29.037091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3574d2e514'
down_revision = '9ac2d0c8d30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=200), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_code',
                              existing_type=sa.VARCHAR(length=10),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_code',
                              existing_type=sa.VARCHAR(length=10),
                              nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
