"""Add used PTO tracking columns to Leave table

Revision ID: 548eb18333bd
Revises: a4d794e9cd20
Create Date: 2026-01-07 20:03:44.931102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548eb18333bd'
down_revision = 'a4d794e9cd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_hours_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advanced_hours_used', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('advanced_hours_used')
        batch_op.drop_column('remaining_hours_used')

    # ### end Alembic commands ###
