"""Add script_run_log table

Revision ID: 6e8a33ec80f0
Revises: c52df3c5abba
Create Date: 2025-12-30 21:14:00.064566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8a33ec80f0'
down_revision = '3d35f95e4cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_run_log')
    # ### end Alembic commands ###
