"""add work_location to users

Revision ID: 742665e5d385
Revises: 6e8a33ec80f0
Create Date: 2026-01-05 18:09:54.225678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742665e5d385'
down_revision = '6e8a33ec80f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('work_location')

    # ### end Alembic commands ###
