"""create audit_log table


Revision ID: 85f2b0312051
Revises: 9ac2d0c8d30f
Create Date: 2025-08-26 21:31:58.095563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f2b0312051'
down_revision = '9ac2d0c8d30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column('id', sa.UUID(), primary_key=True, nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("field", sa.String(length=255), nullable=False),
        sa.Column("old_value", sa.Text, nullable=True),
        sa.Column("new_value", sa.Text, nullable=True),
        sa.Column('created_by', sa.UUID(), sa.ForeignKey(
            'users.id'), nullable=False),
        sa.Column("created_at", sa.DateTime, nullable=False,
                  server_default=sa.text('NOW()')),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_log")

    # ### end Alembic commands ###
