"""Add files table

Revision ID: 9ac2d0c8d30f
Revises: 2e8515fdba71
Create Date: 2025-08-14 21:11:54.553634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac2d0c8d30f'
down_revision = '2e8515fdba71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('id', sa.UUID(), primary_key=True,
                  default=sa.text('uuid_generate_v4()')),
        sa.Column('case_id', sa.UUID(),
                  sa.ForeignKey('cases.id'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('bucket_name', sa.String(), nullable=False),
        sa.Column('s3_key', sa.String(), nullable=False, unique=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')

    # ### end Alembic commands ###
