"""Add advanced_remaining_hours to user_leave_hours table

Revision ID: a4d794e9cd20
Revises: 742665e5d385
Create Date: 2026-01-07 18:27:02.722331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d794e9cd20'
down_revision = '742665e5d385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advanced_remaining_hours', sa.Float(), nullable=True, server_default=sa.text('0.0')))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.drop_column('advanced_remaining_hours')

    # ### end Alembic commands ###
