"""Add replacement_parts column to cases

Revision ID: a7c3e5f19d42
Revises: f6a2b8d4c710
Create Date: 2026-09-28 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7c3e5f19d42'
down_revision = 'f6a2b8d4c710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replacement_parts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('replacement_parts')
    # ### end Alembic commands ###
