"""Add last_accrual_date column

Revision ID: b7853c4bc9b4
Revises: c52df3c5abba
Create Date: 2025-12-30 20:44:09.076085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7853c4bc9b4'
down_revision = 'c52df3c5abba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accrual_date', sa.Date(), nullable=True))
        batch_op.alter_column('remaining_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.alter_column('remaining_hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('last_accrual_date')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
