"""Add return_for_service column to cases

Revision ID: cb2ba67de74c
Revises: 85f2b0312051
Create Date: 2025-11-25 21:27:25.015751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb2ba67de74c'
down_revision = '85f2b0312051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_for_service', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('return_for_service')
    # ### end Alembic commands ###
