"""Add warranty_replacement column to cases

Revision ID: d3f9a1c5e8b2
Revises: b1c4a7e92f10
Create Date: 2026-09-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3f9a1c5e8b2'
down_revision = 'b1c4a7e92f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_replacement', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('warranty_replacement')
    # ### end Alembic commands ###
