"""Add max_remaining_hours to user_leave_hours table

Revision ID: d673821ee9e4
Revises: 742665e5d385
Create Date: 2026-01-07 00:15:15.339937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd673821ee9e4'
down_revision = '742665e5d385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_remaining_hours', sa.Float(), server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_leave_hours', schema=None) as batch_op:
        batch_op.drop_column('max_remaining_hours')

    # ### end Alembic commands ###
