"""Add join_date column to User table

Revision ID: e79c64da420a
Revises: 85dfaee3d0d4
Create Date: 2025-10-30 18:22:18.460511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79c64da420a'
down_revision = '85dfaee3d0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.Date()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('join_date')

    # ### end Alembic commands ###
