"""Widen model_number column on cases to support multiple values

Revision ID: f6a2b8d4c710
Revises: d3f9a1c5e8b2
Create Date: 2026-09-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6a2b8d4c710'
down_revision = 'd3f9a1c5e8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('model_number',
                               existing_type=sa.String(length=50),
                               type_=sa.Text(),
                               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('model_number',
                               existing_type=sa.Text(),
                               type_=sa.String(length=50),
                               existing_nullable=False)
    # ### end Alembic commands ###
