"""Create customers Table

Revision ID: f78653aa3bfa
Revises: 2e8515fdba71
Create Date: 2025-08-11 22:03:43.491602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78653aa3bfa'
down_revision = '3e3574d2e514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
                    sa.Column('id', sa.UUID(), primary_key=True,
                              server_default=sa.text('uuid_generate_v4()')),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('middle_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('phone_code', sa.String(
                        length=10), nullable=False),
                    sa.Column('phone_number', sa.String(
                        length=20), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('street', sa.String(length=100), nullable=True),
                    sa.Column('city', sa.String(length=100), nullable=True),
                    sa.Column('zip_code', sa.String(length=20), nullable=True),
                    sa.Column('state', sa.String(length=100), nullable=True),
                    sa.Column('country', sa.String(length=100), nullable=True),
                    sa.Column('created_by', sa.UUID(), sa.ForeignKey(
                        'users.id'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              nullable=False, server_default=sa.text('NOW()')),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )


def downgrade():
    op.drop_table('customers')
